easy_admin:
    site_name: '<img src="/build/img/logo_admin.png" height="125"/>Dashboard Administrateur'
    design:
        menu:
            - { label: 'Dashboard', route: 'admin_dashboard', default: true, icon: "desktop", css_class: "navlink", controller: App\Controller\AdminController }
            - { label : Stocks }
            - { entity: Stocks, icon: "box-open", css_class: "navlink", children: ['Tout_Le_Stock', 'Rupture']}
            - { label : Utilisateurs }
            - { entity: Utilisateurs, icon: "users", css_class: "navlink" }
            - { entity: Commandes, icon: "file-invoice", css_class: "navlink", children: ['Toutes_Les_Commandes', 'Standby'] }
            - { label : Produits }
            - { entity: Produits, icon: "dolly", css_class: "navlink", children: ["Tous_Les_Produits", "Sans_Photos", "Sans_Etats"]}
            - { entity: Etats, icon: "shopping-cart", css_class: "navlink"}
            - { entity: Photos, icon: "images", css_class: "navlink" }
            - { entity: Categories, icon: "tags", css_class: "navlink" }
        assets:
            css:
                - 'build/admin.css'
            js:
                - 'build/admin.js'
    user: 
        name_property_path: username
    entities:
        Produits:
            class: App\Entity\Product
        Tous_Les_Produits:
            label: "Tous les produits"
            class: App\Entity\Product
            form:
                fields:
                    - name
                    - description
                    - slug
                    - categories
        Sans_Photos:
            label: "Sans Photos"
            class: App\Entity\Product
            list:
                dql_filter: 'entity.photos IS EMPTY'
            disabled_actions: ['new', 'delete', 'edit']
        Sans_Etats:
            label: "Sans Etats"
            class: App\Entity\Product
            list:
                dql_filter: 'entity.states IS EMPTY'
            disabled_actions: ['new', 'delete', 'edit']
        Etats:
            class: App\Entity\State
            list:
                fields:
                    - price
                    - stock
                    - state
                    - product
            form:
                fields:
                    - price
                    - stock
                    - { property: "state", type: 'choice', type_options: {choices: {"Neuf":'Neuf', 'Comme Neuf':'Comme Neuf', 'Bon':'Bon', 'Moyen':'Moyen'} }}
                    - product
        Photos:
            class: App\Entity\Photo
            form:
                fields:
                    - { property: "picture", type: "file_upload", type_options: {upload_dir: public/data}}
                    - product
        Categories:
            class: App\Entity\Category
            label: "Catégories"
            form:
                fields:
                    - name
        Utilisateurs:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - firstname
                    - lastname
                    - { property: "roles", type: 'collection', type_options: {entry_type: "choice", entry_options: {choices: {"User":"ROLE_USER", "Admin":"ROLE_ADMIN" }}}}
            new:
                fields:
                    - { property: "plainPassword", type: 'password'}

        Commandes: 
            class: App\Entity\Order
        Toutes_Les_Commandes:
            class: App\Entity\Order
            label: "Toutes les commandes"
            disabled_actions: ['new', 'delete']
            form:
                fields:
                    - { property: "status", type: 'choice', type_options: {choices: {"Annulée": 0, "En attente": 1, "En préparation": 2, "Envoyée": 3, "Livrée": 4} }}
        Standby:
            class: App\Entity\Order
            list:
                dql_filter: 'entity.status = 1'
            disabled_actions: ['new', 'delete']
            form:
                fields:
                    - { property: "status", type: 'choice', type_options: {choices: {"Annulée": 0, "En attente": 1, "En préparation": 2, "Envoyée": 3, "Livrée": 4} }}
        Stocks:
            class: App\Entity\State
            list:
                dql_filter: 'entity.stock < 10'
                fields:
                    - product
                    - price
                    - stock
                    - state
            form:
                fields:
                    - stock
        Tout_Le_Stock:
            class: App\Entity\State
            label: "Tout le stock"
            list:
                fields:
                    - product
                    - price
                    - stock
                    - state
            form:
                fields:
                    - stock
        Rupture:
            class: App\Entity\State
            list:
                dql_filter: 'entity.stock = 0'
                fields:
                    - product
                    - price
                    - stock
                    - state
                    
            form:
                fields:
                    - stock
