easy_admin:
    site_name: '<img src="/build/img/logo_admin.png" height="125"/>Dashboard Administrateur'
    design:
        menu:
            - { label: 'Dashboard', route: 'admin_dashboard', default: true, icon: "desktop", css_class: "navlink", controller: App\Controller\AdminController }
            - { label : Stocks }
            - { entity: Stocks, icon: "box-open", css_class: "navlink"}
            - { label : Utilisateurs }
            - { entity: Utilisateurs, icon: "users", css_class: "navlink" }
            - { entity: Commandes, icon: "file-invoice", css_class: "navlink" }
            - { label : Produits }
            - { entity: Produits, icon: "dolly", css_class: "navlink"}
            - { entity: Etats, icon: "shopping-cart", css_class: "navlink"}
            - { entity: Photos, icon: "images", css_class: "navlink" }
            - { entity: Categories, icon: "tags", css_class: "navlink" }
        assets:
            css:
                - 'build/admin.css'
            js:
                - 'build/admin.js'
    user: 
        name_property_path: username
    entities:
        Produits:
            class: App\Entity\Product
        Etats:
            class: App\Entity\State
            list:
                fields:
                    - price
                    - stock
                    - state
                    - product
            form:
                fields:
                    - price
                    - stock
                    - { property: "state", type: 'choice', type_options: {choices: {"Neuf":'Neuf', 'Comme Neuf':'Comme Neuf', 'Bon état':'Bon état', 'Moyen':'Moyen'} }}
                    - product
        Photos:
            class: App\Entity\Photo
        Categories:
            class: App\Entity\Category
        Utilisateurs:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - firstname
                    - lastname
                    - { property: "roles", type: 'collection', type_options: {entry_type: "choice", entry_options: {choices: {"User":"ROLE_USER", "Admin":"ROLE_ADMIN" }}}}
            new:
                fields:
                    - { property: "plainPassword", type: 'password'}

        Commandes: 
            class: App\Entity\Order
        Stocks:
            class: App\Entity\State
            list:
                dql_filter: 'entity.stock < 10'
                fields:
                    - product
                    - price
                    - stock
                    - { property: "state", type: 'choice', type_options: {choices: {"Neuf":'Neuf', 'Comme Neuf':'Comme Neuf', 'Bon état':'Bon état', 'Moyen':'Moyen'} }}
                    
            form:
                fields:
                    - stock
