security:
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        db_provider:
            entity:
              class: App\Entity\User
              property: email
      
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: db_provider
            form_login:
              login_path: user_login
              check_path: user_login
            logout:
              path: /logout
              target: /logout_success

    access_control:
        - { path: ^/(register|login)$, allow_if: "is_anonymous()" }
        - { path: ^/event/new$, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }